language: sh
# adapted from https://github.com/mafredri/zsh-async

addons:
  apt:
    packages:
      - build-essential
      - tree

env:
  global:
    - ZSH_DIST=$HOME/.zsh-dist
  matrix:
    # Use _ZSH_VERSION since if ZSH_VERSION is present, travis cacher thinks it
    # is running in zsh and tries to use zsh specific functions.
    - _ZSH_VERSION=5.7.1
    - _ZSH_VERSION=5.6.2
    - _ZSH_VERSION=5.5.1
    - _ZSH_VERSION=5.4.2
    - _ZSH_VERSION=5.3.1
    - _ZSH_VERSION=5.3
    - _ZSH_VERSION=5.2
    - _ZSH_VERSION=5.1.1
    - _ZSH_VERSION=5.0.8
    - _ZSH_VERSION=5.0.2

cache:
  directories:
    - $ZSH_DIST

before_install:
  - source shpec/ci/setup-zsh.zsh $_ZSH_VERSION
  - zsh --version

install:
  - curl -sfL git.io/antibody | sh -s - -b shpec/ci
  - echo "setopt sh_word_split" >> ~/.zshenv

script:
  - zsh shpec/ci/run.zsh
